# Created using wingetcreate 1.9.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.9.0.schema.json

PackageIdentifier: Z7LL.Z7LLres
PackageVersion: "2.5.0"
DefaultLocale: en-US
PackageUrl: https://github.com/Z7LL/Z7LLres
ManifestType: version
ManifestVersion: 1.9.0
